using System.Collections.Generic;
using Godot;

namespace GodotVMF;

public class MDLReader
{
    [System.Flags]
    public enum MDLFlag
    {
        AutogeneratedHitbox = 0x0001,
        UsesEnvCubemap = 0x0002,
        ForceOpaque = 0x0004,
        TranslucentTwopass = 0x0008,
        StaticProp = 0x0010,
        UsesFbTexture = 0x0020,
        HasShadowlod = 0x0040,
        UsesBumpmapping = 0x0080,
        UseShadowlodMaterials = 0x0100,
        Obsolete = 0x0200,
        Unused = 0x0400,
        NoForcedFade = 0x0800,
        ForcePhonomeCrossfade = 0x1000,
        ConstantDirectionalLightDot = 0x2000,
        FlexesConverted = 0x4000,
        BuiltInPreviewMode = 0x8000,
        AmbientBoost = 0x10000,
        DoNotCastShadows = 0x20000,
        CastTextureShadows = 0x40000,
        VertAnimFixedPointScale = 0x200000,
    }

    public class MDLHeader
    {
        public long Address;
        public string Id = "";
        public int Version, Checksum;
        public string Name = "";
        public int Length;
        public Vector3 EyePosition, IllumPosition, HullMin, HullMax, ViewBbMin, ViewBbMax;
        public int Flags;
        public int BoneCount, BoneOffset;
        public int BoneControllerCount, BoneControllerOffset;
        public int HitboxCount, HitboxOffset;
        public int AnimCount, AnimOffset;
        public int LocalAnimCount, LocalAnimOffset;
        public int ActivityListVersion, EventsIndexed;
        public int TextureCount, TextureOffset;
        public int TexturedirCount, TexturedirOffset;
        public int SkinCount, SkinfamilyCount, SkinOffset;
        public int BodypartCount, BodypartOffset;
        public int AttachmentCount, AttachmentOffset;
        public int LocalNodeCount, LocalNodeIndex, LocalNodeNameIndex;
        public int FlexDescCount, FlexDescIndex;
        public int FlexControllerCount, FlexControllerIndex;
        public int IkchainCount, IkchainIndex;
        public int MouthCount, MouthOffset;
        public int LocalPoseParamCount, LocalPoseParamIndex;
        public int SurfacePropIndex;
        public int KeyValueIndex, KeyValueSize;
        public int IkLockCount, IkLockIndex;
        public float Mass;
        public int Contents;
        public int IncludeModelCount, IncludeModelIndex;
        public int VirtualModel;
        public int AnimBlockNameIndex;
        public int AnimBlockCount, AnimBlockIndex, AnimBlockModelIndex;
        public int BoneTableNameIndex;
        public int VertexBase, OffsetBase;
        public int DirectionalLightDot, RootLod, AllowedRootLod, Unused0;
        public int Unused1;
        public int FlexControllerUiCount, FlexControllerUiIndex;
        public float VertAnimFixedPointScale;
        public int Unused2, StudioHdr2Index, Unused3;

        public static MDLHeader Read(FileAccess file)
        {
            var r = new MDLHeader { Address = (long)file.GetPosition() };
            r.Id = ByteReader.ReadStringFixed(file, 4);
            r.Version = ByteReader.ReadSignedInt(file);
            r.Checksum = ByteReader.ReadSignedInt(file);
            r.Name = ByteReader.ReadStringFixed(file, 64);
            r.Length = ByteReader.ReadSignedInt(file);
            r.EyePosition = ByteReader.ReadVector3(file);
            r.IllumPosition = ByteReader.ReadVector3(file);
            r.HullMin = ByteReader.ReadVector3(file);
            r.HullMax = ByteReader.ReadVector3(file);
            r.ViewBbMin = ByteReader.ReadVector3(file);
            r.ViewBbMax = ByteReader.ReadVector3(file);
            r.Flags = ByteReader.ReadSignedInt(file);
            r.BoneCount = ByteReader.ReadSignedInt(file);
            r.BoneOffset = ByteReader.ReadSignedInt(file);
            r.BoneControllerCount = ByteReader.ReadSignedInt(file);
            r.BoneControllerOffset = ByteReader.ReadSignedInt(file);
            r.HitboxCount = ByteReader.ReadSignedInt(file);
            r.HitboxOffset = ByteReader.ReadSignedInt(file);
            r.AnimCount = ByteReader.ReadSignedInt(file);
            r.AnimOffset = ByteReader.ReadSignedInt(file);
            r.LocalAnimCount = ByteReader.ReadSignedInt(file);
            r.LocalAnimOffset = ByteReader.ReadSignedInt(file);
            r.ActivityListVersion = ByteReader.ReadSignedInt(file);
            r.EventsIndexed = ByteReader.ReadSignedInt(file);
            r.TextureCount = ByteReader.ReadSignedInt(file);
            r.TextureOffset = ByteReader.ReadSignedInt(file);
            r.TexturedirCount = ByteReader.ReadSignedInt(file);
            r.TexturedirOffset = ByteReader.ReadSignedInt(file);
            r.SkinCount = ByteReader.ReadSignedInt(file);
            r.SkinfamilyCount = ByteReader.ReadSignedInt(file);
            r.SkinOffset = ByteReader.ReadSignedInt(file);
            r.BodypartCount = ByteReader.ReadSignedInt(file);
            r.BodypartOffset = ByteReader.ReadSignedInt(file);
            r.AttachmentCount = ByteReader.ReadSignedInt(file);
            r.AttachmentOffset = ByteReader.ReadSignedInt(file);
            r.LocalNodeCount = ByteReader.ReadSignedInt(file);
            r.LocalNodeIndex = ByteReader.ReadSignedInt(file);
            r.LocalNodeNameIndex = ByteReader.ReadSignedInt(file);
            r.FlexDescCount = ByteReader.ReadSignedInt(file);
            r.FlexDescIndex = ByteReader.ReadSignedInt(file);
            r.FlexControllerCount = ByteReader.ReadSignedInt(file);
            r.FlexControllerIndex = ByteReader.ReadSignedInt(file);
            r.IkchainCount = ByteReader.ReadSignedInt(file);
            r.IkchainIndex = ByteReader.ReadSignedInt(file);
            r.MouthCount = ByteReader.ReadSignedInt(file);
            r.MouthOffset = ByteReader.ReadSignedInt(file);
            r.LocalPoseParamCount = ByteReader.ReadSignedInt(file);
            r.LocalPoseParamIndex = ByteReader.ReadSignedInt(file);
            r.SurfacePropIndex = ByteReader.ReadSignedInt(file);
            r.KeyValueIndex = ByteReader.ReadSignedInt(file);
            r.KeyValueSize = ByteReader.ReadSignedInt(file);
            r.IkLockCount = ByteReader.ReadSignedInt(file);
            r.IkLockIndex = ByteReader.ReadSignedInt(file);
            r.Mass = file.GetFloat();
            r.Contents = ByteReader.ReadSignedInt(file);
            r.IncludeModelCount = ByteReader.ReadSignedInt(file);
            r.IncludeModelIndex = ByteReader.ReadSignedInt(file);
            r.VirtualModel = ByteReader.ReadSignedInt(file);
            r.AnimBlockNameIndex = ByteReader.ReadSignedInt(file);
            r.AnimBlockCount = ByteReader.ReadSignedInt(file);
            r.AnimBlockIndex = ByteReader.ReadSignedInt(file);
            r.AnimBlockModelIndex = ByteReader.ReadSignedInt(file);
            r.BoneTableNameIndex = ByteReader.ReadSignedInt(file);
            r.VertexBase = ByteReader.ReadSignedInt(file);
            r.OffsetBase = ByteReader.ReadSignedInt(file);
            r.DirectionalLightDot = file.Get8();
            r.RootLod = file.Get8();
            r.AllowedRootLod = file.Get8();
            r.Unused0 = file.Get8();
            r.Unused1 = ByteReader.ReadSignedInt(file);
            r.FlexControllerUiCount = ByteReader.ReadSignedInt(file);
            r.FlexControllerUiIndex = ByteReader.ReadSignedInt(file);
            r.VertAnimFixedPointScale = file.GetFloat();
            r.Unused2 = ByteReader.ReadSignedInt(file);
            r.StudioHdr2Index = ByteReader.ReadSignedInt(file);
            r.Unused3 = ByteReader.ReadSignedInt(file);
            return r;
        }
    }

    public class MDLTexture
    {
        public long Address;
        public int NameOffset, Flags, Used, Unused, Material, ClientMaterial;
        public int[] Unused2 = new int[10];
        public string Name = "";

        public static MDLTexture Read(FileAccess file)
        {
            var r = new MDLTexture { Address = (long)file.GetPosition() };
            r.NameOffset = ByteReader.ReadSignedInt(file);
            r.Flags = ByteReader.ReadSignedInt(file);
            r.Used = ByteReader.ReadSignedInt(file);
            r.Unused = ByteReader.ReadSignedInt(file);
            r.Material = ByteReader.ReadSignedInt(file);
            r.ClientMaterial = ByteReader.ReadSignedInt(file);
            for (int i = 0; i < 10; i++) r.Unused2[i] = ByteReader.ReadSignedInt(file);
            return r;
        }
    }

    public class MDLBone
    {
        public long Address;
        public int Id;
        public int NameOffset, Parent;
        public int[] Bonecontrollers = new int[6];
        public Vector3 Pos;
        public Quaternion Quat;
        public Vector3 Rot, PosScale, RotScale;
        public Transform3D PosToBone;
        public Quaternion QAlignment;
        public int Flags, ProcType, ProcIndex, PhysicsBone, SurfacePropIndex, Contents;
        public string Name = "";
        public string SurfaceProp = "";

        public static MDLBone Read(FileAccess file)
        {
            var r = new MDLBone { Address = (long)file.GetPosition() };
            r.NameOffset = ByteReader.ReadSignedInt(file);
            r.Parent = ByteReader.ReadSignedInt(file);
            for (int i = 0; i < 6; i++) r.Bonecontrollers[i] = ByteReader.ReadSignedInt(file);
            r.Pos = ByteReader.ReadVector3(file);
            r.Quat = ByteReader.ReadQuaternion(file);
            r.Rot = ByteReader.ReadEulerVector(file);
            r.PosScale = ByteReader.ReadVector3(file);
            r.RotScale = ByteReader.ReadVector3(file);
            r.PosToBone = ByteReader.ReadTransform3D(file);
            r.QAlignment = ByteReader.ReadQuaternion(file);
            r.Flags = ByteReader.ReadSignedInt(file);
            r.ProcType = ByteReader.ReadSignedInt(file);
            r.ProcIndex = ByteReader.ReadSignedInt(file);
            r.PhysicsBone = ByteReader.ReadSignedInt(file);
            r.SurfacePropIndex = ByteReader.ReadSignedInt(file);
            r.Contents = ByteReader.ReadSignedInt(file);
            for (int i = 0; i < 32; i++) file.Get8(); // unused bytes
            return r;
        }
    }

    public class MDLBodyPart
    {
        public long Address;
        public int NameIndex, NumModels, Base, ModelIndex;
        public string Name = "";
        public List<MDLModel> Models = new();

        public static MDLBodyPart Read(FileAccess file)
        {
            var r = new MDLBodyPart { Address = (long)file.GetPosition() };
            r.NameIndex = ByteReader.ReadSignedInt(file);
            r.NumModels = ByteReader.ReadSignedInt(file);
            r.Base = ByteReader.ReadSignedInt(file);
            r.ModelIndex = ByteReader.ReadSignedInt(file);
            return r;
        }
    }

    public class MDLModel
    {
        public long Address;
        public string Name = "";
        public int Type;
        public float BoundingRadius;
        public int NumMeshes, MeshOffset;
        public int NumVerts, VertIndex, TangentsIndex;
        public int NumAttachments, AttachmentIndex;
        public int NumEyeballs, EyeballIndex;
        public List<MDLMesh> Meshes = new();

        public static MDLModel Read(FileAccess file)
        {
            var r = new MDLModel { Address = (long)file.GetPosition() };
            r.Name = ByteReader.ReadStringFixed(file, 64);
            r.Type = ByteReader.ReadSignedInt(file);
            r.BoundingRadius = file.GetFloat();
            r.NumMeshes = ByteReader.ReadSignedInt(file);
            r.MeshOffset = ByteReader.ReadSignedInt(file);
            r.NumVerts = ByteReader.ReadSignedInt(file);
            r.VertIndex = ByteReader.ReadSignedInt(file);
            r.TangentsIndex = ByteReader.ReadSignedInt(file);
            r.NumAttachments = ByteReader.ReadSignedInt(file);
            r.AttachmentIndex = ByteReader.ReadSignedInt(file);
            r.NumEyeballs = ByteReader.ReadSignedInt(file);
            r.EyeballIndex = ByteReader.ReadSignedInt(file);
            for (int i = 0; i < 10; i++) ByteReader.ReadSignedInt(file); // unused
            return r;
        }
    }

    public class MDLMesh
    {
        public long Address;
        public int Material, ModelOffset, VertexCount, VertexIndexStart;
        public int FlexesCount, FlexesOffset;
        public int MaterialType, MaterialParam, MeshId;
        public Vector3 Center;
        public int Unused0;
        public int[] NumberVerticesLod = new int[8];
        public int[] VertexOffsetLod = new int[8];

        public static MDLMesh Read(FileAccess file)
        {
            var r = new MDLMesh { Address = (long)file.GetPosition() };
            r.Material = ByteReader.ReadSignedInt(file);
            r.ModelOffset = ByteReader.ReadSignedInt(file);
            r.VertexCount = ByteReader.ReadSignedInt(file);
            r.VertexIndexStart = ByteReader.ReadSignedInt(file);
            r.FlexesCount = ByteReader.ReadSignedInt(file);
            r.FlexesOffset = ByteReader.ReadSignedInt(file);
            r.MaterialType = ByteReader.ReadSignedInt(file);
            r.MaterialParam = ByteReader.ReadSignedInt(file);
            r.MeshId = ByteReader.ReadSignedInt(file);
            r.Center = ByteReader.ReadVector3(file);
            r.Unused0 = ByteReader.ReadSignedInt(file);
            for (int i = 0; i < 8; i++) r.NumberVerticesLod[i] = ByteReader.ReadSignedInt(file);
            for (int i = 0; i < 8; i++) r.VertexOffsetLod[i] = ByteReader.ReadSignedInt(file);
            return r;
        }
    }

    public MDLHeader? Header;
    public List<string> TextureDirs = new();
    public List<MDLTexture> Textures = new();
    public List<MDLBone> Bones = new();
    public List<MDLBodyPart> BodyParts = new();
    public List<List<int>> SkinFamilies = new();
    public string SourcePath = "";

    public string ModelName => System.IO.Path.GetFileNameWithoutExtension(SourcePath);

    private FileAccess? _file;

    public MDLReader(string sourcePath)
    {
        SourcePath = sourcePath;
        _file = FileAccess.Open(sourcePath, FileAccess.ModeFlags.Read);
        if (_file == null) return;

        Header = MDLHeader.Read(_file);
        ReadTextureData();
        ReadBones();
        ReadBodyParts();
        ReadSkinFamilies();

        _file.Close();
        _file = null;
    }

    private void ReadTextureData()
    {
        if (_file == null || Header == null) return;
        _file.Seek((ulong)Header.TexturedirOffset);
        _file.Seek(_file.Get32());
        for (int i = 0; i < Header.TexturedirCount; i++)
            TextureDirs.Add(ByteReader.ReadString(_file));

        Textures = ByteReader.ReadArray(_file, Header.Address, Header.TextureOffset, Header.TextureCount, MDLTexture.Read);
        foreach (var tex in Textures)
            tex.Name = ByteReader.ReadString(_file, tex.Address + tex.NameOffset);
    }

    private void ReadBones()
    {
        if (_file == null || Header == null) return;
        Bones = ByteReader.ReadArray(_file, Header.Address, Header.BoneOffset, Header.BoneCount, MDLBone.Read);
        for (int i = 0; i < Bones.Count; i++)
        {
            var bone = Bones[i];
            bone.Name = ByteReader.ReadString(_file, bone.Address + bone.NameOffset);
            bone.SurfaceProp = ByteReader.ReadString(_file, bone.Address + bone.SurfacePropIndex);
            bone.Id = i;
        }
    }

    private void ReadBodyParts()
    {
        if (_file == null || Header == null) return;
        BodyParts = ByteReader.ReadArray(_file, Header.Address, Header.BodypartOffset, Header.BodypartCount, MDLBodyPart.Read);
        foreach (var bp in BodyParts)
        {
            bp.Name = ByteReader.ReadString(_file, bp.Address + bp.NameIndex);
            bp.Models = ByteReader.ReadArray(_file, bp.Address, bp.ModelIndex, bp.NumModels, MDLModel.Read);
            foreach (var model in bp.Models)
                model.Meshes = ByteReader.ReadArray(_file, model.Address, model.MeshOffset, model.NumMeshes, MDLMesh.Read);
        }
    }

    private void ReadSkinFamilies()
    {
        if (_file == null || Header == null) return;
        _file.Seek((ulong)Header.SkinOffset);
        for (int i = 0; i < Header.SkinfamilyCount * Header.SkinCount; i++)
        {
            int j = i / Header.SkinCount;
            if (SkinFamilies.Count <= j) SkinFamilies.Add(new List<int>());
            SkinFamilies[j].Add(ByteReader.ReadSignedShort(_file));
        }
    }

    public List<string> GetPossibleMaterialPaths()
    {
        var materials = new List<string>();
        foreach (var tex in Textures)
            foreach (var dir in TextureDirs)
                materials.Add(VMFUtils.NormalizePath(dir + "/" + tex.Name));
        return materials;
    }
}
